package com.asecor.extranet.data;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

// Generated 21/04/2020 02:39:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.asecor.extranet.util.DataUtil;

/**
 * City generated by hbm2java
 */
public class Adherentes implements java.io.Serializable {

	private Integer id;
	private Integer codSolicitud;
	private Integer codParentesco;
	private String apellido;
	private String nombre;
	private Date fechaNacimiento;
	private String nroDocumento;
	public Adherentes() {
	}
	
	public Adherentes(Integer id, Integer codSolicitud, Integer codParetensco, String apellido, String nombre,
			Date fechaNacimiento, String nroDocumento) {
		super();
		this.id = id;
		this.codSolicitud = codSolicitud;
		this.codParentesco = codParetensco;
		this.apellido = apellido;
		this.nombre = nombre;
		this.fechaNacimiento = fechaNacimiento;
		this.nroDocumento = nroDocumento;
	}

	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getCodSolicitud() {
		return codSolicitud;
	}
	public void setCodSolicitud(Integer codSolicitud) {
		this.codSolicitud = codSolicitud;
	}
	public Integer getCodParentesco() {
		return codParentesco;
	}
	public void setCodParentesco(Integer codParetensco) {
		this.codParentesco = codParetensco;
	}
	public String getApellido() {
		return apellido;
	}
	public void setApellido(String apellido) {
		this.apellido = apellido;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public Date getFechaNacimiento() {
		
		
		return fechaNacimiento;
	}
	public String getFechaNacimientoString() {
		SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
		if(this.fechaNacimiento!=null)
		return sdf.format(fechaNacimiento);
		else return " ";
	}
	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}
	public String getNroDocumento() {
		return nroDocumento;
	}
	public void setNroDocumento(String nroDocumento) {
		this.nroDocumento = nroDocumento;
	}

	public String getParentesco() {
		
		if(codParentesco==2)
			return "HIJO/HIJA";
		if(codParentesco==3)
			return "CONJUGE";
		else
			return "OTRO";
		
	}
	
	public String getNombreYApellido() {
		if(this.nombre==null)
			nombre=" ";
		if(this.apellido==null)
			apellido=" ";
		return (this.nombre.concat( "  ").concat(this.apellido)).toUpperCase();
	}
	public String getEdad() {
	
		DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.S");
		if(null!=fechaNacimiento) {
		LocalDate fechaNac = LocalDate.parse(this.fechaNacimiento.toString(), fmt);
		LocalDate ahora = LocalDate.now();
		
		int edad=DataUtil.calculateAge(fechaNac, ahora);
		
		return String.valueOf(edad);
		}else
			return " ";
	}

}
