package com.asecor.extranet.data;

// Generated 21/04/2020 02:39:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class Cobranzas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Polizas polizas;
	
	private Float importe;
	private Float importePago;
	private Date fechaInicio;
	private Date fechaVto;
	private Date fechaCobranza;
	private String estado;
	private String codFormaPago;
	private Integer nroCuota;
	private Integer codTipoMovimiento;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Float getImporte() {
		return importe;
	}
	public void setImporte(Float importe) {
		this.importe = importe;
	}
	public Float getImportePago() {
		return importePago;
	}
	public void setImportePago(Float importePago) {
		this.importePago = importePago;
	}
	public Date getFechaVto() {
		return fechaVto;
	}
	public void setFechaVto(Date fechaVto) {
		this.fechaVto = fechaVto;
	}
	public Date getFechaCobranza() {
		return fechaCobranza;
	}
	public void setFechaCobranza(Date fechaCobranza) {
		this.fechaCobranza = fechaCobranza;
	}
	public String getCodFormaPago() {
		return codFormaPago;
	}
	public void setCodFormaPago(String codFormaPago) {
		this.codFormaPago = codFormaPago;
	}
	public Integer getNroCuota() {
		return nroCuota;
	}
	public void setNroCuota(Integer nroCuota) {
		this.nroCuota = nroCuota;
	}
	public Polizas getPolizas() {
		return polizas;
	}
	public void setPolizas(Polizas polizas) {
		this.polizas = polizas;
	}

	public String getFormaPago() {
		String resultado="CA";
		if(this.codFormaPago==null)
			resultado="CA";
		else {
		if(this.codFormaPago.equalsIgnoreCase("CC"))
			resultado="CUENTA CORRIENTE" ;
		if(this.codFormaPago.equalsIgnoreCase("CA"))
			resultado="CAJA DE AHORRO"; 
		if(this.codFormaPago.equalsIgnoreCase("TC"))
			resultado="TARJETA DE CREDITO"; 
		if(this.codFormaPago.equalsIgnoreCase("CAP"))
			resultado="DESCUENTO ADM PUBLICA"; 
		if(this.codFormaPago.equalsIgnoreCase("JUB"))
			resultado="DESCUENTO JUB DE ADM PUBLICA"; 
		}
		return resultado;
	}
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	public Integer getCodTipoMovimiento() {
		return codTipoMovimiento;
	}
	public void setCodTipoMovimiento(Integer codTipoMovimiento) {
		this.codTipoMovimiento = codTipoMovimiento;
	}
	public Date getFechaInicio() {
		return fechaInicio;
	}
	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	
}
